### ISSUE TITLE
I deleted the backup and didn't restore it! How can I restore my Mii Channel?

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [FIX94/wuphax#2]

**Comment by Coolguy1260** [comment]
Same thing happened to me, but I didn't bother to restore it. I thought of NUS Downloader, but now that I've done the research, it won't work.  I think this thread will help: https://gbatemp.net/threads/possible-safe-to-reinstall-mii-channel-on-vwii-menu.440492/
